#Build stage
FROM golang:1.18.2-alpine

WORKDIR /app

COPY . .

RUN apk add netcat-openbsd

RUN go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest

RUN go install github.com/cosmtrek/air@latest

RUN go mod download