version: '3.1'
services:
  # postgres:
  #   image: postgres:13-alpine
  #   restart: always
  #   environment:
  #     - POSTGRES_DB=${POSTGRES_DB}
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #     - POSTGRES_USER=${POSTGRES_USER}
  #   ports: 
  #     - "5432:5432"
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "8080:8080"
    environment:
      - DB_SOURCE=${DB_SOURCE}
    volumes:
      - ./:/app
    # depends_on:
    #   - postgres
    # entrypoint: [ "/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh" ]
    entrypoint: [ "/app/start.sh" ]
    command: [ "air" ]
